export const STORAGE_KEY = "skeddo-app-v3";
export const uid = () =>
  typeof crypto !== "undefined" && crypto.randomUUID
    ? crypto.randomUUID()
    : Date.now().toString(36) + Math.random().toString(36).slice(2, 10) + Math.random().toString(36).slice(2, 10);

/* ─── DIRECTORY PROGRAMS (browsable/discoverable) ─── */
export const DIRECTORY_PROGRAMS = [
  // --- Sports ---
  { id: "dir-1", name: "Multi-Sport Day Camp", provider: "City of Vancouver", category: "Sports", cost: 235, days: "Mon\u2013Fri", times: "9:00\u20134:00", startDate: "2026-07-06", endDate: "2026-07-10", seasonType: "Summer Camp", ageMin: 6, ageMax: 12, location: "Hillcrest Community Centre", neighbourhood: "Riley Park", registrationUrl: "https://vancouver.ca/parks-recreation", description: "A fun-filled week of soccer, basketball, floor hockey, and more. Campers rotate through different sports each day with trained coaches." },
  { id: "dir-2", name: "Tennis Junior Academy", provider: "Vancouver Tennis Club", category: "Sports", cost: 310, days: "Mon\u2013Fri", times: "9:00\u201312:00", startDate: "2026-07-13", endDate: "2026-07-17", seasonType: "Summer Camp", ageMin: 7, ageMax: 14, location: "Stanley Park Tennis Courts", neighbourhood: "West End", registrationUrl: "", description: "Beginner to intermediate tennis instruction. Small group sizes, equipment provided." },
  { id: "dir-3", name: "Skateboarding Camp", provider: "Radbrad Skate School", category: "Sports", cost: 275, days: "Mon\u2013Fri", times: "10:00\u20132:00", startDate: "2026-07-20", endDate: "2026-07-24", seasonType: "Summer Camp", ageMin: 8, ageMax: 15, location: "China Creek Skatepark", neighbourhood: "Mount Pleasant", registrationUrl: "", description: "All skill levels welcome. Helmets and pads provided. Learn tricks, park etiquette, and build confidence on wheels." },
  { id: "dir-4", name: "Little Kickers Soccer", provider: "North Shore FC", category: "Sports", cost: 165, days: "Sat", times: "9:30\u201310:30", startDate: "2026-06-01", endDate: "2026-08-29", seasonType: "Year-Round", ageMin: 3, ageMax: 5, location: "Mahon Park", neighbourhood: "North Vancouver", registrationUrl: "", description: "Fun, non-competitive soccer for preschoolers. Focus on coordination, teamwork, and having a blast." },
  { id: "dir-5", name: "Rock Climbing Camp", provider: "Hive Climbing Gym", category: "Sports", cost: 345, days: "Mon\u2013Fri", times: "9:00\u20133:00", startDate: "2026-08-04", endDate: "2026-08-08", seasonType: "Summer Camp", ageMin: 8, ageMax: 14, location: "Hive Bouldering Gym", neighbourhood: "East Vancouver", registrationUrl: "", description: "Indoor bouldering, top-rope climbing, and teamwork challenges. All equipment included." },

  // --- Arts ---
  { id: "dir-6", name: "Pottery & Ceramics Camp", provider: "Shadbolt Centre", category: "Arts", cost: 290, days: "Mon\u2013Fri", times: "9:30\u20133:30", startDate: "2026-07-06", endDate: "2026-07-10", seasonType: "Summer Camp", ageMin: 7, ageMax: 12, location: "Shadbolt Centre for the Arts", neighbourhood: "Burnaby", registrationUrl: "", description: "Hand-building, wheel throwing, and glazing. Kids take home their fired creations at the end of the week." },
  { id: "dir-7", name: "Animation & Cartooning", provider: "Arts Umbrella", category: "Arts", cost: 385, days: "Mon\u2013Fri", times: "9:00\u20134:00", startDate: "2026-07-13", endDate: "2026-07-17", seasonType: "Summer Camp", ageMin: 9, ageMax: 14, location: "Arts Umbrella, Granville Island", neighbourhood: "Granville Island", registrationUrl: "", description: "Learn character design, storyboarding, and frame-by-frame animation using both digital and traditional media." },
  { id: "dir-8", name: "Musical Theatre Workshop", provider: "Stage Door Youth", category: "Arts", cost: 425, days: "Mon\u2013Fri", times: "9:00\u20134:00", startDate: "2026-07-20", endDate: "2026-07-31", seasonType: "Summer Camp", ageMin: 8, ageMax: 14, location: "Waterfront Theatre", neighbourhood: "Granville Island", registrationUrl: "", description: "Two-week intensive culminating in a short performance for families. Singing, dancing, and acting." },
  { id: "dir-9", name: "Photography for Teens", provider: "Langara College Continuing Studies", category: "Arts", cost: 195, days: "Mon/Wed/Fri", times: "10:00\u20131:00", startDate: "2026-08-04", endDate: "2026-08-15", seasonType: "Summer Camp", ageMin: 12, ageMax: 17, location: "Langara College", neighbourhood: "South Vancouver", registrationUrl: "", description: "Learn composition, lighting, and editing. Bring your own camera or phone. Outdoor photo walks included." },

  // --- STEM ---
  { id: "dir-10", name: "Robotics & Engineering", provider: "STEM World Academy", category: "STEM", cost: 395, days: "Mon\u2013Fri", times: "9:00\u20134:00", startDate: "2026-07-06", endDate: "2026-07-10", seasonType: "Summer Camp", ageMin: 8, ageMax: 13, location: "STEM World Lab", neighbourhood: "Richmond", registrationUrl: "", description: "Build and program robots using LEGO Mindstorms and Arduino. Team challenges and competitions throughout the week." },
  { id: "dir-11", name: "Game Design & Scratch Coding", provider: "Code Ninjas", category: "STEM", cost: 325, days: "Mon\u2013Fri", times: "9:00\u20133:00", startDate: "2026-07-13", endDate: "2026-07-17", seasonType: "Summer Camp", ageMin: 7, ageMax: 11, location: "Code Ninjas Kerrisdale", neighbourhood: "Kerrisdale", registrationUrl: "", description: "Design your own video games using Scratch, learn logic and problem-solving through play." },
  { id: "dir-12", name: "Science Explorers", provider: "Science World", category: "STEM", cost: 355, days: "Mon\u2013Fri", times: "9:00\u20134:00", startDate: "2026-07-20", endDate: "2026-07-24", seasonType: "Summer Camp", ageMin: 6, ageMax: 10, location: "Science World", neighbourhood: "False Creek", registrationUrl: "", description: "Hands-on experiments in chemistry, physics, and biology. Behind-the-scenes tours of Science World exhibits." },
  { id: "dir-13", name: "Minecraft Coding Camp", provider: "TechSprouts", category: "STEM", cost: 280, days: "Mon\u2013Fri", times: "9:30\u201312:30", startDate: "2026-08-04", endDate: "2026-08-08", seasonType: "Summer Camp", ageMin: 7, ageMax: 12, location: "TechSprouts Lab", neighbourhood: "Mount Pleasant", registrationUrl: "", description: "Learn JavaScript basics through Minecraft modding. Build custom worlds, mobs, and items." },

  // --- Outdoor ---
  { id: "dir-14", name: "Wilderness Adventure Camp", provider: "Metro Vancouver Parks", category: "Outdoor", cost: 265, days: "Mon\u2013Fri", times: "9:00\u20134:00", startDate: "2026-07-06", endDate: "2026-07-10", seasonType: "Summer Camp", ageMin: 8, ageMax: 12, location: "Lynn Canyon Park", neighbourhood: "North Vancouver", registrationUrl: "", description: "Hiking, creek exploration, shelter building, and nature journaling. Pack a lunch and wear sturdy shoes." },
  { id: "dir-15", name: "Farm & Garden Camp", provider: "UBC Farm", category: "Outdoor", cost: 310, days: "Mon\u2013Fri", times: "9:00\u20133:00", startDate: "2026-07-13", endDate: "2026-07-17", seasonType: "Summer Camp", ageMin: 5, ageMax: 9, location: "UBC Farm", neighbourhood: "UBC", registrationUrl: "", description: "Seed planting, harvesting, farm animals, and nature crafts. Kids connect with where their food comes from." },
  { id: "dir-16", name: "Kayaking & Paddleboarding", provider: "Deep Cove Kayak", category: "Outdoor", cost: 340, days: "Mon\u2013Fri", times: "9:00\u20133:00", startDate: "2026-07-27", endDate: "2026-07-31", seasonType: "Summer Camp", ageMin: 10, ageMax: 15, location: "Deep Cove", neighbourhood: "North Vancouver", registrationUrl: "", description: "Learn kayaking and SUP on Indian Arm. Water safety, marine ecology, and beach games." },
  { id: "dir-17", name: "Forest School", provider: "Wild Roots Education", category: "Outdoor", cost: 225, days: "Tue/Thu", times: "9:00\u201312:00", startDate: "2026-06-01", endDate: "2026-08-28", seasonType: "Year-Round", ageMin: 3, ageMax: 6, location: "Jericho Beach Park", neighbourhood: "Point Grey", registrationUrl: "", description: "Nature-based play and learning for preschoolers. Rain or shine, all seasons." },

  // --- Music ---
  { id: "dir-18", name: "Rock Band Camp", provider: "School of Rock", category: "Music", cost: 450, days: "Mon\u2013Fri", times: "9:00\u20134:00", startDate: "2026-07-06", endDate: "2026-07-17", seasonType: "Summer Camp", ageMin: 9, ageMax: 15, location: "School of Rock Vancouver", neighbourhood: "Kitsilano", registrationUrl: "", description: "Form a band, learn songs, and perform a live show for family and friends on the final day." },
  { id: "dir-19", name: "Ukulele for Beginners", provider: "Community Music School", category: "Music", cost: 120, days: "Wed", times: "10:00\u201311:00", startDate: "2026-07-08", endDate: "2026-08-12", seasonType: "Summer Camp", ageMin: 6, ageMax: 10, location: "Britannia Community Centre", neighbourhood: "Commercial Drive", registrationUrl: "", description: "No experience needed. Ukuleles provided. Learn chords, strumming, and sing-alongs." },

  // --- Life Skills ---
  { id: "dir-20", name: "Junior Bakers Camp", provider: "Baking Bunch", category: "Life Skills", cost: 295, days: "Mon\u2013Fri", times: "9:00\u20131:00", startDate: "2026-07-13", endDate: "2026-07-17", seasonType: "Summer Camp", ageMin: 7, ageMax: 12, location: "Baking Bunch Kitchen", neighbourhood: "Main Street", registrationUrl: "", description: "Bread, cookies, pizza dough, and more. Kids learn measuring, food safety, and take treats home daily." },
  { id: "dir-21", name: "Babysitter's Training", provider: "Red Cross", category: "Life Skills", cost: 85, days: "Sat", times: "9:00\u20134:30", startDate: "2026-07-11", endDate: "2026-07-11", seasonType: "Summer Camp", ageMin: 11, ageMax: 15, location: "Various Community Centres", neighbourhood: "Various", registrationUrl: "", description: "Official Red Cross certification. First aid basics, child development, and age-appropriate activities." },
  { id: "dir-22", name: "Financial Literacy for Kids", provider: "Junior Achievement BC", category: "Life Skills", cost: 0, days: "Sat", times: "10:00\u201312:00", startDate: "2026-07-18", endDate: "2026-08-08", seasonType: "Summer Camp", ageMin: 9, ageMax: 13, location: "Vancouver Public Library", neighbourhood: "Downtown", registrationUrl: "", description: "Free workshop series on saving, budgeting, and entrepreneurship basics." },

  // --- Spring Break ---
  { id: "dir-23", name: "Spring Break Sports Blast", provider: "City of Vancouver", category: "Sports", cost: 210, days: "Mon\u2013Fri", times: "9:00\u20134:00", startDate: "2027-03-15", endDate: "2027-03-19", seasonType: "Spring Break", ageMin: 6, ageMax: 12, location: "Killarney Community Centre", neighbourhood: "Killarney", registrationUrl: "", description: "A week of basketball, dodgeball, swimming, and outdoor games over spring break." },
  { id: "dir-24", name: "Spring Break Art Camp", provider: "Arts Umbrella", category: "Arts", cost: 340, days: "Mon\u2013Fri", times: "9:00\u20134:00", startDate: "2027-03-15", endDate: "2027-03-19", seasonType: "Spring Break", ageMin: 6, ageMax: 12, location: "Arts Umbrella, Granville Island", neighbourhood: "Granville Island", registrationUrl: "", description: "Painting, sculpture, mixed media, and printmaking. All materials provided." },

  // --- Pro-D Day ---
  { id: "dir-25", name: "Pro-D Day Adventure", provider: "Pedalheads", category: "Outdoor", cost: 75, days: "Fri", times: "9:00\u20134:00", startDate: "2026-10-23", endDate: "2026-10-23", seasonType: "Pro-D Day", ageMin: 5, ageMax: 12, location: "Various Parks", neighbourhood: "Various", registrationUrl: "", description: "Biking, hiking, and outdoor games for Pro-D days. Drop-off and pick-up included." },
  { id: "dir-26", name: "Pro-D LEGO Robotics", provider: "Bricks 4 Kidz", category: "STEM", cost: 65, days: "Fri", times: "9:00\u20133:00", startDate: "2026-11-20", endDate: "2026-11-20", seasonType: "Pro-D Day", ageMin: 5, ageMax: 12, location: "Bricks 4 Kidz Centre", neighbourhood: "Richmond", registrationUrl: "", description: "Build motorized LEGO models and explore engineering concepts. One-day workshop." },

  // --- After School ---
  { id: "dir-27", name: "After School Art Club", provider: "Shadbolt Centre", category: "Arts", cost: 180, days: "Tue/Thu", times: "3:30\u20135:30", startDate: "2026-09-08", endDate: "2026-12-10", seasonType: "After School", ageMin: 6, ageMax: 11, location: "Shadbolt Centre for the Arts", neighbourhood: "Burnaby", registrationUrl: "", description: "Drawing, painting, and mixed media after school. Snack included." },
  { id: "dir-28", name: "Homework Club & Tutoring", provider: "Kumon", category: "Academic", cost: 200, days: "Mon/Wed", times: "4:00\u20135:30", startDate: "2026-09-08", endDate: "2026-12-14", seasonType: "After School", ageMin: 6, ageMax: 14, location: "Kumon Oakridge", neighbourhood: "Oakridge", registrationUrl: "", description: "Math and reading support with trained instructors. Personalized learning plans." },

  // --- Christmas ---
  { id: "dir-29", name: "Holiday Art Camp", provider: "Hillside Arts Centre", category: "Arts", cost: 190, days: "Mon\u2013Fri", times: "9:00\u20133:00", startDate: "2026-12-21", endDate: "2026-12-24", seasonType: "Christmas Camp", ageMin: 5, ageMax: 12, location: "Hillside Arts Centre", neighbourhood: "Kitsilano", registrationUrl: "", description: "Festive crafts, ornament making, and creative projects during the holiday break." },
  { id: "dir-30", name: "Winter Break Hockey Camp", provider: "Canucks Sports", category: "Sports", cost: 325, days: "Mon\u2013Fri", times: "8:00\u201312:00", startDate: "2026-12-28", endDate: "2027-01-01", seasonType: "Christmas Camp", ageMin: 6, ageMax: 14, location: "Scotia Barn", neighbourhood: "Burnaby", registrationUrl: "", description: "Skating and hockey skills development during the winter break. All equipment provided." },
];
