#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, '..', 'src', 'data', 'programs.json');
const programs = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

let fixCount = 0;
let addCount = 0;

// ── 1. STATUS FIXES ────────────────────────────────────────────────────────

// IDs 1394–1425 + champlain-cc-1: Full/Waitlist → Coming Soon
// (all have registrationDate=2026-04-08, registration not yet open on 2026-04-05)
const toComingSoon = [
  1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403,
  1404, 1405, 1406, 1407, 1408, 1409, 1410, 1411, 1412, 1413,
  1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423,
  1424, 1425,
  'champlain-cc-1'
];

for (const prog of programs) {
  const id = prog.id;
  if (toComingSoon.includes(id) || toComingSoon.includes(String(id))) {
    if (prog.enrollmentStatus !== 'Coming Soon') {
      prog.enrollmentStatus = 'Coming Soon';
      fixCount++;
    }
  }
}

// COV-607069: Open → Full/Waitlist (0 openings, 4 on waitlist confirmed on live page)
for (const prog of programs) {
  if (String(prog.id) === 'COV-607069') {
    prog.enrollmentStatus = 'Full/Waitlist';
    fixCount++;
  }
}

// ── 2. ADD NEW PROGRAMS ────────────────────────────────────────────────────

const CH = {
  provider: 'City of Vancouver - Champlain Heights Cmty Centre',
  address: '3350 Maquinna Drive, Vancouver, BC',
  neighbourhood: 'Champlain Heights',
  lat: 49.2165,
  lng: -123.03,
  city: 'Vancouver',
  confirmed2026: true,
  priceVerified: true,
  urlVerified: true,
  registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=57',
};

const newPrograms = [
  // ── Acro Jazz I & II ─────────────────────────────────────────────────────
  {
    id: 'COV-608521',
    name: 'Acro Jazz I & II',
    provider: CH.provider,
    category: 'Dance',
    subcategory: 'Jazz',
    description: 'Acro Jazz dance class for children ages 8–12. Combines acrobatic skills with jazz dance techniques.',
    ageMin: 8,
    ageMax: 12,
    startDate: '2026-04-12',
    endDate: '2026-06-21',
    startTime: '11:30',
    endTime: '12:10',
    days: ['Sunday'],
    cost: 100,
    costNote: '$100 for the session (no class May 17)',
    enrollmentStatus: 'Open',
    registrationDate: null,
    address: CH.address,
    neighbourhood: CH.neighbourhood,
    lat: CH.lat,
    lng: CH.lng,
    city: CH.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/detail/608521',
    confirmed2026: CH.confirmed2026,
    priceVerified: CH.priceVerified,
    urlVerified: CH.urlVerified,
    tags: ['dance', 'acro', 'jazz', 'kids'],
    repeating: 'weekly',
  },

  // ── Adapted Family Open Gym (May) ─────────────────────────────────────────
  {
    id: 'COV-609576',
    name: 'Adapted Family Open Gym',
    provider: CH.provider,
    category: 'Sports & Recreation',
    subcategory: 'Adapted',
    description: 'Adapted family open gym session for children with diverse abilities and their families. Drop-in format.',
    ageMin: 5,
    ageMax: 17,
    startDate: '2026-05-16',
    endDate: '2026-05-16',
    startTime: '09:30',
    endTime: '10:30',
    days: ['Saturday'],
    cost: 0,
    costNote: 'Free program',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-04-08',
    address: CH.address,
    neighbourhood: CH.neighbourhood,
    lat: CH.lat,
    lng: CH.lng,
    city: CH.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/detail/609576',
    confirmed2026: CH.confirmed2026,
    priceVerified: CH.priceVerified,
    urlVerified: CH.urlVerified,
    tags: ['adapted', 'inclusive', 'open-gym', 'family'],
  },

  // ── Adapted Family Open Gym (Jul–Aug) ────────────────────────────────────
  {
    id: 'COV-610736',
    name: 'Adapted Family Open Gym',
    provider: CH.provider,
    category: 'Sports & Recreation',
    subcategory: 'Adapted',
    description: 'Summer adapted family open gym sessions for children with diverse abilities and their families. Drop-in format.',
    ageMin: 5,
    ageMax: 17,
    startDate: '2026-07-25',
    endDate: '2026-08-22',
    startTime: '11:45',
    endTime: '12:45',
    days: ['Saturday'],
    cost: 0,
    costNote: 'Free program',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-04-08',
    address: CH.address,
    neighbourhood: CH.neighbourhood,
    lat: CH.lat,
    lng: CH.lng,
    city: CH.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/detail/610736',
    confirmed2026: CH.confirmed2026,
    priceVerified: CH.priceVerified,
    urlVerified: CH.urlVerified,
    tags: ['adapted', 'inclusive', 'open-gym', 'family', 'summer'],
    repeating: 'weekly',
  },

  // ── Adventures at Avalon Pond (4 sessions) ──────────────────────────────
  {
    id: 'COV-608866',
    name: 'Adventures at Avalon Pond',
    provider: CH.provider,
    category: 'Nature & Outdoors',
    subcategory: 'Environmental Education',
    description: 'Outdoor nature exploration at Everett Crowley Park Avalon Pond. Children discover local aquatic ecosystems and wildlife.',
    ageMin: 7,
    ageMax: 10,
    startDate: '2026-05-20',
    endDate: '2026-05-20',
    startTime: '16:30',
    endTime: '17:45',
    days: ['Wednesday'],
    cost: 20,
    costNote: '$20 per session',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-04-08',
    address: 'Everett Crowley Park, Vancouver, BC',
    neighbourhood: 'Champlain Heights',
    lat: 49.2124,
    lng: -123.0255,
    city: 'Vancouver',
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/detail/608866',
    confirmed2026: CH.confirmed2026,
    priceVerified: CH.priceVerified,
    urlVerified: CH.urlVerified,
    tags: ['nature', 'outdoor', 'pond', 'ecology', 'kids'],
  },
  {
    id: 'COV-608867',
    name: 'Adventures at Avalon Pond',
    provider: CH.provider,
    category: 'Nature & Outdoors',
    subcategory: 'Environmental Education',
    description: 'Outdoor nature exploration at Everett Crowley Park Avalon Pond. Children discover local aquatic ecosystems and wildlife.',
    ageMin: 7,
    ageMax: 10,
    startDate: '2026-05-27',
    endDate: '2026-05-27',
    startTime: '16:30',
    endTime: '17:45',
    days: ['Wednesday'],
    cost: 20,
    costNote: '$20 per session',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-04-08',
    address: 'Everett Crowley Park, Vancouver, BC',
    neighbourhood: 'Champlain Heights',
    lat: 49.2124,
    lng: -123.0255,
    city: 'Vancouver',
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/detail/608867',
    confirmed2026: CH.confirmed2026,
    priceVerified: CH.priceVerified,
    urlVerified: CH.urlVerified,
    tags: ['nature', 'outdoor', 'pond', 'ecology', 'kids'],
  },
  {
    id: 'COV-608868',
    name: 'Adventures at Avalon Pond',
    provider: CH.provider,
    category: 'Nature & Outdoors',
    subcategory: 'Environmental Education',
    description: 'Outdoor nature exploration at Everett Crowley Park Avalon Pond. Children discover local aquatic ecosystems and wildlife.',
    ageMin: 7,
    ageMax: 10,
    startDate: '2026-06-10',
    endDate: '2026-06-10',
    startTime: '16:30',
    endTime: '17:45',
    days: ['Wednesday'],
    cost: 20,
    costNote: '$20 per session',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-04-08',
    address: 'Everett Crowley Park, Vancouver, BC',
    neighbourhood: 'Champlain Heights',
    lat: 49.2124,
    lng: -123.0255,
    city: 'Vancouver',
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/detail/608868',
    confirmed2026: CH.confirmed2026,
    priceVerified: CH.priceVerified,
    urlVerified: CH.urlVerified,
    tags: ['nature', 'outdoor', 'pond', 'ecology', 'kids'],
  },
  {
    id: 'COV-608869',
    name: 'Adventures at Avalon Pond',
    provider: CH.provider,
    category: 'Nature & Outdoors',
    subcategory: 'Environmental Education',
    description: 'Outdoor nature exploration at Everett Crowley Park Avalon Pond. Children discover local aquatic ecosystems and wildlife.',
    ageMin: 7,
    ageMax: 10,
    startDate: '2026-06-17',
    endDate: '2026-06-17',
    startTime: '16:30',
    endTime: '17:45',
    days: ['Wednesday'],
    cost: 20,
    costNote: '$20 per session',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-04-08',
    address: 'Everett Crowley Park, Vancouver, BC',
    neighbourhood: 'Champlain Heights',
    lat: 49.2124,
    lng: -123.0255,
    city: 'Vancouver',
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/detail/608869',
    confirmed2026: CH.confirmed2026,
    priceVerified: CH.priceVerified,
    urlVerified: CH.urlVerified,
    tags: ['nature', 'outdoor', 'pond', 'ecology', 'kids'],
  },

  // ── Amphibian and Nature Walk (3 sessions) ──────────────────────────────
  {
    id: 'COV-608858',
    name: 'Amphibian and Nature Walk',
    provider: CH.provider,
    category: 'Nature & Outdoors',
    subcategory: 'Environmental Education',
    description: 'Evening nature walk to observe amphibians and local wildlife. Meet at Kerr St Parking Lot (Everett Crowley Park). All ages welcome.',
    ageMin: 0,
    ageMax: 17,
    startDate: '2026-05-07',
    endDate: '2026-05-07',
    startTime: '18:00',
    endTime: '19:30',
    days: ['Thursday'],
    cost: 0,
    costNote: 'Free program',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-04-08',
    address: 'Kerr St Parking Lot, Everett Crowley Park, Vancouver, BC',
    neighbourhood: 'Champlain Heights',
    lat: 49.2124,
    lng: -123.0255,
    city: 'Vancouver',
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/detail/608858',
    confirmed2026: CH.confirmed2026,
    priceVerified: CH.priceVerified,
    urlVerified: CH.urlVerified,
    tags: ['nature', 'amphibians', 'walk', 'family', 'evening'],
    ageSpanJustified: 'Family program explicitly open to all ages — no distinct age-group segments',
  },
  {
    id: 'COV-608859',
    name: 'Amphibian and Nature Walk',
    provider: CH.provider,
    category: 'Nature & Outdoors',
    subcategory: 'Environmental Education',
    description: 'Evening nature walk to observe amphibians and local wildlife. Meet at Kerr St Parking Lot (Everett Crowley Park). All ages welcome.',
    ageMin: 0,
    ageMax: 17,
    startDate: '2026-06-11',
    endDate: '2026-06-11',
    startTime: '18:00',
    endTime: '19:30',
    days: ['Thursday'],
    cost: 0,
    costNote: 'Free program',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-04-08',
    address: 'Kerr St Parking Lot, Everett Crowley Park, Vancouver, BC',
    neighbourhood: 'Champlain Heights',
    lat: 49.2124,
    lng: -123.0255,
    city: 'Vancouver',
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/detail/608859',
    confirmed2026: CH.confirmed2026,
    priceVerified: CH.priceVerified,
    urlVerified: CH.urlVerified,
    tags: ['nature', 'amphibians', 'walk', 'family', 'evening'],
    ageSpanJustified: 'Family program explicitly open to all ages — no distinct age-group segments',
  },
  {
    id: 'COV-608861',
    name: 'Amphibian and Nature Walk',
    provider: CH.provider,
    category: 'Nature & Outdoors',
    subcategory: 'Environmental Education',
    description: 'Evening nature walk to observe amphibians and local wildlife. Meet at Kerr St Parking Lot (Everett Crowley Park). All ages welcome.',
    ageMin: 0,
    ageMax: 17,
    startDate: '2026-07-02',
    endDate: '2026-07-02',
    startTime: '18:00',
    endTime: '19:30',
    days: ['Thursday'],
    cost: 0,
    costNote: 'Free program',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-04-08',
    address: 'Kerr St Parking Lot, Everett Crowley Park, Vancouver, BC',
    neighbourhood: 'Champlain Heights',
    lat: 49.2124,
    lng: -123.0255,
    city: 'Vancouver',
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/detail/608861',
    confirmed2026: CH.confirmed2026,
    priceVerified: CH.priceVerified,
    urlVerified: CH.urlVerified,
    tags: ['nature', 'amphibians', 'walk', 'family', 'evening'],
    ageSpanJustified: 'Family program explicitly open to all ages — no distinct age-group segments',
  },

  // ── Amphibian Survey (4 sessions) ────────────────────────────────────────
  {
    id: 'COV-608852',
    name: 'Amphibian Survey',
    provider: CH.provider,
    category: 'Nature & Outdoors',
    subcategory: 'Environmental Education',
    description: 'Evening amphibian survey at Everett Crowley Park. Participants help monitor local amphibian populations. Meet at Kerr St Parking Lot.',
    ageMin: 10,
    ageMax: 17,
    startDate: '2026-04-16',
    endDate: '2026-04-16',
    startTime: '18:00',
    endTime: '19:30',
    days: ['Thursday'],
    cost: 0,
    costNote: 'Free program',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-04-08',
    address: 'Kerr St Parking Lot, Everett Crowley Park, Vancouver, BC',
    neighbourhood: 'Champlain Heights',
    lat: 49.2124,
    lng: -123.0255,
    city: 'Vancouver',
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/detail/608852',
    confirmed2026: CH.confirmed2026,
    priceVerified: CH.priceVerified,
    urlVerified: CH.urlVerified,
    tags: ['nature', 'amphibians', 'survey', 'ecology', 'youth'],
  },
  {
    id: 'COV-608854',
    name: 'Amphibian Survey',
    provider: CH.provider,
    category: 'Nature & Outdoors',
    subcategory: 'Environmental Education',
    description: 'Evening amphibian survey at Everett Crowley Park. Participants help monitor local amphibian populations. Meet at Kerr St Parking Lot.',
    ageMin: 10,
    ageMax: 17,
    startDate: '2026-04-21',
    endDate: '2026-04-21',
    startTime: '18:00',
    endTime: '19:30',
    days: ['Tuesday'],
    cost: 0,
    costNote: 'Free program',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-04-08',
    address: 'Kerr St Parking Lot, Everett Crowley Park, Vancouver, BC',
    neighbourhood: 'Champlain Heights',
    lat: 49.2124,
    lng: -123.0255,
    city: 'Vancouver',
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/detail/608854',
    confirmed2026: CH.confirmed2026,
    priceVerified: CH.priceVerified,
    urlVerified: CH.urlVerified,
    tags: ['nature', 'amphibians', 'survey', 'ecology', 'youth'],
  },
  {
    id: 'COV-608855',
    name: 'Amphibian Survey',
    provider: CH.provider,
    category: 'Nature & Outdoors',
    subcategory: 'Environmental Education',
    description: 'Evening amphibian survey at Everett Crowley Park. Participants help monitor local amphibian populations. Meet at Kerr St Parking Lot.',
    ageMin: 10,
    ageMax: 17,
    startDate: '2026-05-19',
    endDate: '2026-05-19',
    startTime: '18:00',
    endTime: '19:30',
    days: ['Tuesday'],
    cost: 0,
    costNote: 'Free program',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-04-08',
    address: 'Kerr St Parking Lot, Everett Crowley Park, Vancouver, BC',
    neighbourhood: 'Champlain Heights',
    lat: 49.2124,
    lng: -123.0255,
    city: 'Vancouver',
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/detail/608855',
    confirmed2026: CH.confirmed2026,
    priceVerified: CH.priceVerified,
    urlVerified: CH.urlVerified,
    tags: ['nature', 'amphibians', 'survey', 'ecology', 'youth'],
  },
  {
    id: 'COV-608856',
    name: 'Amphibian Survey',
    provider: CH.provider,
    category: 'Nature & Outdoors',
    subcategory: 'Environmental Education',
    description: 'Evening amphibian survey at Everett Crowley Park. Participants help monitor local amphibian populations. Meet at Kerr St Parking Lot.',
    ageMin: 10,
    ageMax: 17,
    startDate: '2026-05-26',
    endDate: '2026-05-26',
    startTime: '18:00',
    endTime: '19:30',
    days: ['Tuesday'],
    cost: 0,
    costNote: 'Free program',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-04-08',
    address: 'Kerr St Parking Lot, Everett Crowley Park, Vancouver, BC',
    neighbourhood: 'Champlain Heights',
    lat: 49.2124,
    lng: -123.0255,
    city: 'Vancouver',
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/detail/608856',
    confirmed2026: CH.confirmed2026,
    priceVerified: CH.priceVerified,
    urlVerified: CH.urlVerified,
    tags: ['nature', 'amphibians', 'survey', 'ecology', 'youth'],
  },
];

// Check for duplicates before adding
const existingIds = new Set(programs.map(p => String(p.id)));
for (const prog of newPrograms) {
  if (existingIds.has(String(prog.id))) {
    console.log(`SKIP (already exists): ${prog.id}`);
  } else {
    programs.push(prog);
    existingIds.add(String(prog.id));
    addCount++;
    console.log(`ADDED: ${prog.id} — ${prog.name}`);
  }
}

// ── 3. WRITE OUTPUT ────────────────────────────────────────────────────────
fs.writeFileSync(dataPath, JSON.stringify(programs, null, 2) + '\n');

console.log(`\nDone. Fixed: ${fixCount}, Added: ${addCount}, Total programs: ${programs.length}`);
