#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, '..', 'src', 'data', 'programs.json');
const programs = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

let fixCount = 0;
let addCount = 0;

// ── 1. STATUS FIXES ────────────────────────────────────────────────────────
// IDs 1505–1523 (17): Full/Waitlist → Coming Soon (registrationDate=2026-04-08)
const toComingSoon = [
  1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512,
  1513, 1514, 1515, 1518, 1519, 1520, 1521, 1522, 1523,
];
for (const prog of programs) {
  if (toComingSoon.includes(prog.id)) {
    const old = prog.enrollmentStatus;
    prog.enrollmentStatus = 'Coming Soon';
    if (old !== 'Coming Soon') {
      fixCount++;
    }
  }
}
console.log(`Status fixes applied: ${fixCount}`);

// ── 2. ADD NEW PROGRAMS ────────────────────────────────────────────────────
const HC = {
  provider: 'City of Vancouver - Hastings Cmty Centre',
  address: '3096 E Hastings St, Vancouver, BC V5K 2A3',
  neighbourhood: 'Hastings-Sunrise',
  lat: 49.2812,
  lng: -123.0387,
  city: 'Vancouver',
  confirmed2026: true,
  priceVerified: true,
  urlVerified: true,
};

// Hastings Park (East) location — across the street from main CC
const HP = {
  address: 'Hastings Park (East), 3096 E Hastings St area, Vancouver, BC',
  neighbourhood: 'Hastings-Sunrise',
  lat: 49.2812,
  lng: -123.0387,
};

const newPrograms = [
  // ── Active Jazz Funk and Pop Dance & KPOP Sampler ────────────────────────
  {
    id: 'COV-605310',
    name: 'Active Jazz Funk and Pop Dance & KPOP Sampler',
    provider: HC.provider,
    category: 'Dance',
    subcategory: 'Hip Hop',
    activityType: 'Dance',
    description: 'Sample Jazz Funk, Pop Dance, and Korean Pop (KPOP) styles in a fun and energetic class. Open to ages 6-13.',
    ageMin: 6,
    ageMax: 13,
    startDate: '2026-04-08',
    endDate: '2026-06-10',
    startTime: '4:45 PM',
    endTime: '5:45 PM',
    days: 'Wed',
    cost: 160,
    costNote: '$160 for the session',
    enrollmentStatus: 'Open',
    registrationDate: null,
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/605310',
    address: HC.address,
    neighbourhood: HC.neighbourhood,
    lat: HC.lat,
    lng: HC.lng,
    city: HC.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=44',
    confirmed2026: HC.confirmed2026,
    priceVerified: HC.priceVerified,
    urlVerified: HC.urlVerified,
    season: 'Spring',
    tags: ['dance', 'KPOP', 'jazz funk', 'hip hop', 'kids', 'youth'],
    repeating: 'weekly',
    indoorOutdoor: 'Indoor',
  },

  // ── Adult & Family Decorative Sushi Workshop ─────────────────────────────
  {
    id: 'COV-614155',
    name: 'Adult & Family Decorative Sushi Workshop',
    provider: HC.provider,
    category: 'Arts',
    subcategory: 'Cooking & Crafts',
    activityType: 'Workshop',
    description: 'Decorative sushi-making workshop for adults and families. Children welcome with an adult.',
    ageMin: 6,
    ageMax: 17,
    startDate: '2026-05-09',
    endDate: '2026-05-09',
    startTime: '2:00 PM',
    endTime: '3:30 PM',
    days: 'Sat',
    cost: 60,
    costNote: '$60 per person (family workshop)',
    enrollmentStatus: 'Open',
    registrationDate: null,
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/614155',
    address: HC.address,
    neighbourhood: HC.neighbourhood,
    lat: HC.lat,
    lng: HC.lng,
    city: HC.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=44',
    confirmed2026: HC.confirmed2026,
    priceVerified: HC.priceVerified,
    urlVerified: HC.urlVerified,
    season: 'Spring',
    tags: ['sushi', 'cooking', 'workshop', 'family'],
    ageSpanJustified: 'Family program open to all ages 6+ — no age-band segments, children attend with adults',
    indoorOutdoor: 'Indoor',
  },
  {
    id: 'COV-614156',
    name: 'Adult & Family Decorative Sushi Workshop',
    provider: HC.provider,
    category: 'Arts',
    subcategory: 'Cooking & Crafts',
    activityType: 'Workshop',
    description: 'Decorative sushi-making workshop for adults and families. Children welcome with an adult.',
    ageMin: 6,
    ageMax: 17,
    startDate: '2026-06-13',
    endDate: '2026-06-13',
    startTime: '2:00 PM',
    endTime: '3:30 PM',
    days: 'Sat',
    cost: 60,
    costNote: '$60 per person (family workshop)',
    enrollmentStatus: 'Open',
    registrationDate: null,
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/614156',
    address: HC.address,
    neighbourhood: HC.neighbourhood,
    lat: HC.lat,
    lng: HC.lng,
    city: HC.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=44',
    confirmed2026: HC.confirmed2026,
    priceVerified: HC.priceVerified,
    urlVerified: HC.urlVerified,
    season: 'Spring',
    tags: ['sushi', 'cooking', 'workshop', 'family'],
    ageSpanJustified: 'Family program open to all ages 6+ — no age-band segments, children attend with adults',
    indoorOutdoor: 'Indoor',
  },

  // ── Adventures in Music - Mixed Ages (Spring, missing sessions) ───────────
  {
    id: 'COV-611398',
    name: 'Adventures in Music - Mixed Ages',
    provider: HC.provider,
    category: 'Music',
    subcategory: 'Early Childhood Music',
    activityType: 'Music',
    description: 'Interactive music program for toddlers and preschoolers ages 1-5. Songs, movement, instruments, and music play.',
    ageMin: 1,
    ageMax: 5,
    startDate: '2026-04-09',
    endDate: '2026-06-18',
    startTime: '9:15 AM',
    endTime: '10:00 AM',
    days: 'Thu',
    cost: 165,
    costNote: '$165 for 11 sessions',
    enrollmentStatus: 'Open',
    registrationDate: null,
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/611398',
    address: HC.address,
    neighbourhood: HC.neighbourhood,
    lat: HC.lat,
    lng: HC.lng,
    city: HC.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=44',
    confirmed2026: HC.confirmed2026,
    priceVerified: HC.priceVerified,
    urlVerified: HC.urlVerified,
    season: 'Spring',
    tags: ['music', 'toddler', 'preschool', 'early childhood'],
    repeating: 'weekly',
    indoorOutdoor: 'Indoor',
  },
  {
    id: 'COV-611402',
    name: 'Adventures in Music - Mixed Ages',
    provider: HC.provider,
    category: 'Music',
    subcategory: 'Early Childhood Music',
    activityType: 'Music',
    description: 'Interactive music program for toddlers and preschoolers ages 1-5. Songs, movement, instruments, and music play.',
    ageMin: 1,
    ageMax: 5,
    startDate: '2026-04-11',
    endDate: '2026-06-20',
    startTime: '9:15 AM',
    endTime: '10:00 AM',
    days: 'Sat',
    cost: 165,
    costNote: '$165 for 11 sessions',
    enrollmentStatus: 'Full/Waitlist',
    registrationDate: null,
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/611402',
    address: HC.address,
    neighbourhood: HC.neighbourhood,
    lat: HC.lat,
    lng: HC.lng,
    city: HC.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=44',
    confirmed2026: HC.confirmed2026,
    priceVerified: HC.priceVerified,
    urlVerified: HC.urlVerified,
    season: 'Spring',
    tags: ['music', 'toddler', 'preschool', 'early childhood'],
    repeating: 'weekly',
    indoorOutdoor: 'Indoor',
  },
  {
    id: 'COV-611403',
    name: 'Adventures in Music - Mixed Ages',
    provider: HC.provider,
    category: 'Music',
    subcategory: 'Early Childhood Music',
    activityType: 'Music',
    description: 'Interactive music program for toddlers and preschoolers ages 1-5. Songs, movement, instruments, and music play.',
    ageMin: 1,
    ageMax: 5,
    startDate: '2026-04-11',
    endDate: '2026-06-20',
    startTime: '10:15 AM',
    endTime: '11:00 AM',
    days: 'Sat',
    cost: 165,
    costNote: '$165 for 11 sessions',
    enrollmentStatus: 'Full/Waitlist',
    registrationDate: null,
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/611403',
    address: HC.address,
    neighbourhood: HC.neighbourhood,
    lat: HC.lat,
    lng: HC.lng,
    city: HC.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=44',
    confirmed2026: HC.confirmed2026,
    priceVerified: HC.priceVerified,
    urlVerified: HC.urlVerified,
    season: 'Spring',
    tags: ['music', 'toddler', 'preschool', 'early childhood'],
    repeating: 'weekly',
    indoorOutdoor: 'Indoor',
  },
  {
    id: 'COV-611404',
    name: 'Adventures in Music - Mixed Ages',
    provider: HC.provider,
    category: 'Music',
    subcategory: 'Early Childhood Music',
    activityType: 'Music',
    description: 'Interactive music program for toddlers and preschoolers ages 1-5. Songs, movement, instruments, and music play.',
    ageMin: 1,
    ageMax: 5,
    startDate: '2026-04-11',
    endDate: '2026-06-20',
    startTime: '11:15 AM',
    endTime: '12:00 PM',
    days: 'Sat',
    cost: 165,
    costNote: '$165 for 11 sessions',
    enrollmentStatus: 'Open',
    registrationDate: null,
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/611404',
    address: HC.address,
    neighbourhood: HC.neighbourhood,
    lat: HC.lat,
    lng: HC.lng,
    city: HC.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=44',
    confirmed2026: HC.confirmed2026,
    priceVerified: HC.priceVerified,
    urlVerified: HC.urlVerified,
    season: 'Spring',
    tags: ['music', 'toddler', 'preschool', 'early childhood'],
    repeating: 'weekly',
    indoorOutdoor: 'Indoor',
  },

  // ── Adventures in Music - Mixed Ages (Summer, Hastings Park East) ─────────
  {
    id: 'COV-611476',
    name: 'Adventures in Music - Mixed Ages',
    provider: HC.provider,
    category: 'Music',
    subcategory: 'Early Childhood Music',
    activityType: 'Music',
    description: 'Interactive outdoor music program for toddlers and preschoolers ages 1-5. Held at Hastings Park (East), across the street from the main community centre.',
    ageMin: 1,
    ageMax: 5,
    startDate: '2026-07-09',
    endDate: '2026-08-13',
    startTime: '9:15 AM',
    endTime: '10:00 AM',
    days: 'Thu',
    cost: 90,
    costNote: '$90 for 6 summer sessions at Hastings Park (East)',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-06-13',
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/611476',
    address: 'Hastings Park (East), Vancouver, BC',
    neighbourhood: HC.neighbourhood,
    lat: HC.lat,
    lng: HC.lng,
    city: HC.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=44',
    confirmed2026: HC.confirmed2026,
    priceVerified: HC.priceVerified,
    urlVerified: HC.urlVerified,
    season: 'Summer',
    tags: ['music', 'toddler', 'preschool', 'early childhood', 'outdoor', 'park'],
    repeating: 'weekly',
    indoorOutdoor: 'Outdoor',
  },
  {
    id: 'COV-611477',
    name: 'Adventures in Music - Mixed Ages',
    provider: HC.provider,
    category: 'Music',
    subcategory: 'Early Childhood Music',
    activityType: 'Music',
    description: 'Interactive outdoor music program for toddlers and preschoolers ages 1-5. Held at Hastings Park (East), across the street from the main community centre.',
    ageMin: 1,
    ageMax: 5,
    startDate: '2026-07-09',
    endDate: '2026-08-13',
    startTime: '10:15 AM',
    endTime: '11:00 AM',
    days: 'Thu',
    cost: 90,
    costNote: '$90 for 6 summer sessions at Hastings Park (East)',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-06-13',
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/611477',
    address: 'Hastings Park (East), Vancouver, BC',
    neighbourhood: HC.neighbourhood,
    lat: HC.lat,
    lng: HC.lng,
    city: HC.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=44',
    confirmed2026: HC.confirmed2026,
    priceVerified: HC.priceVerified,
    urlVerified: HC.urlVerified,
    season: 'Summer',
    tags: ['music', 'toddler', 'preschool', 'early childhood', 'outdoor', 'park'],
    repeating: 'weekly',
    indoorOutdoor: 'Outdoor',
  },

  // ── Alphabet Explorers ───────────────────────────────────────────────────
  {
    id: 'COV-613000',
    name: 'Alphabet Explorers',
    provider: HC.provider,
    category: 'Education',
    subcategory: 'Early Literacy',
    activityType: 'Education',
    description: 'Explore letters, sounds, and words through simple activities, books, storytelling, and fun games! No class May 16.',
    ageMin: 4,
    ageMax: 5,
    startDate: '2026-04-11',
    endDate: '2026-06-06',
    startTime: '11:00 AM',
    endTime: '12:15 PM',
    days: 'Sat',
    cost: 108,
    costNote: '$108 for 8 sessions. No class May 16.',
    enrollmentStatus: 'Open',
    registrationDate: null,
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/613000',
    address: HC.address,
    neighbourhood: HC.neighbourhood,
    lat: HC.lat,
    lng: HC.lng,
    city: HC.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=44',
    confirmed2026: HC.confirmed2026,
    priceVerified: HC.priceVerified,
    urlVerified: HC.urlVerified,
    season: 'Spring',
    tags: ['literacy', 'alphabet', 'preschool', 'education', 'reading'],
    repeating: 'weekly',
    indoorOutdoor: 'Indoor',
  },
];

const existingIds = new Set(programs.map(p => String(p.id)));
for (const prog of newPrograms) {
  if (existingIds.has(String(prog.id))) {
    console.log(`SKIP (exists): ${prog.id}`);
  } else {
    programs.push(prog);
    existingIds.add(String(prog.id));
    addCount++;
    console.log(`ADDED: ${prog.id} — ${prog.name} (${prog.startDate})`);
  }
}

fs.writeFileSync(dataPath, JSON.stringify(programs, null, 2) + '\n');
console.log(`\nDone. Fixed: ${fixCount}, Added: ${addCount}, Total: ${programs.length}`);
