#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, '..', 'src', 'data', 'programs.json');
const programs = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

let fixCount = 0;
let addCount = 0;

// ── 1. STATUS FIXES ────────────────────────────────────────────────────────
// IDs 1679–1711 + marpole-oakridge-cc-1: Full/Waitlist → Coming Soon
// All have registrationDate=2026-04-08; registration not yet open on 2026-04-06
const toComingSoon = [
  1679, 1680, 1681, 1683, 1685, 1687, 1688,
  1690, 1691, 1692, 1693, 1694, 1695, 1696,
  1697, 1698, 1699, 1700, 1701, 1702, 1703,
  1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711,
  'marpole-oakridge-cc-1',
];

for (const prog of programs) {
  const id = prog.id;
  if (toComingSoon.includes(id) || toComingSoon.includes(String(id))) {
    if (prog.enrollmentStatus !== 'Coming Soon') {
      prog.enrollmentStatus = 'Coming Soon';
      fixCount++;
    }
  }
}

// ── 2. ADD NEW PROGRAMS ────────────────────────────────────────────────────
const MO = {
  provider: 'City of Vancouver - Marpole-Oakridge Cmty Centre',
  address: '990 West 59th Avenue, Vancouver, BC',
  neighbourhood: 'Marpole',
  lat: 49.2128,
  lng: -123.1206,
  city: 'Vancouver',
  confirmed2026: true,
  priceVerified: true,
  urlVerified: true,
};

const newPrograms = [
  // ── Badminton Lessons ────────────────────────────────────────────────────
  {
    id: 'COV-606890',
    name: 'Badminton Lessons - Beginner I',
    provider: MO.provider,
    category: 'Sports & Recreation',
    subcategory: 'Badminton',
    activityType: 'Racket Sport',
    description: 'The perfect starting point for those new to badminton. Focuses on grip, footwork, strokes, and simple game rules in a fun environment. No prior experience needed. Please bring your own racquet.',
    ageMin: 8,
    ageMax: 10,
    startDate: '2026-04-11',
    endDate: '2026-06-27',
    startTime: '11:15 AM',
    endTime: '12:00 PM',
    days: 'Sat',
    cost: 80,
    costNote: '$80 for 10 sessions. No class May 16 & Jun 6.',
    enrollmentStatus: 'Full/Waitlist',
    registrationDate: null,
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/606890',
    address: MO.address,
    neighbourhood: MO.neighbourhood,
    lat: MO.lat,
    lng: MO.lng,
    city: MO.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=54',
    confirmed2026: MO.confirmed2026,
    priceVerified: MO.priceVerified,
    urlVerified: MO.urlVerified,
    season: 'Spring',
    tags: ['badminton', 'racket', 'beginner', 'kids'],
    repeating: 'weekly',
    indoorOutdoor: 'Indoor',
  },
  {
    id: 'COV-606892',
    name: 'Badminton Lessons - Beginner II',
    provider: MO.provider,
    category: 'Sports & Recreation',
    subcategory: 'Badminton',
    activityType: 'Racket Sport',
    description: 'Beginner-friendly badminton for pre-teens and teens. Develop grip, footwork, serving, and rallying skills. No experience needed. Please bring your own racquet.',
    ageMin: 10,
    ageMax: 14,
    startDate: '2026-04-11',
    endDate: '2026-06-27',
    startTime: '12:00 PM',
    endTime: '12:55 PM',
    days: 'Sat',
    cost: 105,
    costNote: '$105 for 10 sessions. No class May 16 & Jun 6.',
    enrollmentStatus: 'Full/Waitlist',
    registrationDate: null,
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/606892',
    address: MO.address,
    neighbourhood: MO.neighbourhood,
    lat: MO.lat,
    lng: MO.lng,
    city: MO.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=54',
    confirmed2026: MO.confirmed2026,
    priceVerified: MO.priceVerified,
    urlVerified: MO.urlVerified,
    season: 'Spring',
    tags: ['badminton', 'racket', 'beginner', 'youth'],
    repeating: 'weekly',
    indoorOutdoor: 'Indoor',
  },
  {
    id: 'COV-606894',
    name: 'Badminton Lessons - Intermediate',
    provider: MO.provider,
    category: 'Sports & Recreation',
    subcategory: 'Badminton',
    activityType: 'Racket Sport',
    description: 'For players with basic badminton experience. Improve footwork, shot variety, game strategy, and match play. Please bring your own racquet. Not an automatic continuation of Beginner I or II — consult coach for placement.',
    ageMin: 10,
    ageMax: 14,
    startDate: '2026-04-11',
    endDate: '2026-06-27',
    startTime: '12:55 PM',
    endTime: '1:55 PM',
    days: 'Sat',
    cost: 105,
    costNote: '$105 for 10 sessions. No class May 16 & Jun 6.',
    enrollmentStatus: 'Full/Waitlist',
    registrationDate: null,
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/606894',
    address: MO.address,
    neighbourhood: MO.neighbourhood,
    lat: MO.lat,
    lng: MO.lng,
    city: MO.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=54',
    confirmed2026: MO.confirmed2026,
    priceVerified: MO.priceVerified,
    urlVerified: MO.urlVerified,
    season: 'Spring',
    tags: ['badminton', 'racket', 'intermediate', 'youth'],
    repeating: 'weekly',
    indoorOutdoor: 'Indoor',
  },

  // ── Basketball DRIVE Training Academy ────────────────────────────────────
  {
    id: 'COV-604967',
    name: 'Basketball - DRIVE Training Academy',
    provider: MO.provider,
    category: 'Sports & Recreation',
    subcategory: 'Basketball',
    activityType: 'Team Sport',
    description: 'Athletes develop basketball fundamentals including shooting, passing, triple threat, scoring moves, and team concepts in a fun and competitive environment. Bring water bottle and proper attire.',
    ageMin: 6,
    ageMax: 8,
    startDate: '2026-04-07',
    endDate: '2026-06-23',
    startTime: '3:35 PM',
    endTime: '4:35 PM',
    days: 'Tue',
    cost: 132,
    costNote: '$132 for the session (Tuesdays)',
    enrollmentStatus: 'Open',
    registrationDate: null,
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/604967',
    address: MO.address,
    neighbourhood: MO.neighbourhood,
    lat: MO.lat,
    lng: MO.lng,
    city: MO.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=54',
    confirmed2026: MO.confirmed2026,
    priceVerified: MO.priceVerified,
    urlVerified: MO.urlVerified,
    season: 'Spring',
    tags: ['basketball', 'team sport', 'kids'],
    repeating: 'weekly',
    indoorOutdoor: 'Indoor',
  },
  {
    id: 'COV-604968',
    name: 'Basketball - DRIVE Training Academy',
    provider: MO.provider,
    category: 'Sports & Recreation',
    subcategory: 'Basketball',
    activityType: 'Team Sport',
    description: 'Athletes develop basketball fundamentals including shooting, passing, triple threat, scoring moves, and team concepts in a fun and competitive environment. Bring water bottle and proper attire.',
    ageMin: 6,
    ageMax: 8,
    startDate: '2026-04-09',
    endDate: '2026-06-25',
    startTime: '3:35 PM',
    endTime: '4:35 PM',
    days: 'Thu',
    cost: 132,
    costNote: '$132 for the session (Thursdays)',
    enrollmentStatus: 'Open',
    registrationDate: null,
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/604968',
    address: MO.address,
    neighbourhood: MO.neighbourhood,
    lat: MO.lat,
    lng: MO.lng,
    city: MO.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=54',
    confirmed2026: MO.confirmed2026,
    priceVerified: MO.priceVerified,
    urlVerified: MO.urlVerified,
    season: 'Spring',
    tags: ['basketball', 'team sport', 'kids'],
    repeating: 'weekly',
    indoorOutdoor: 'Indoor',
  },
  {
    id: 'COV-604972',
    name: 'Basketball - DRIVE Training Academy',
    provider: MO.provider,
    category: 'Sports & Recreation',
    subcategory: 'Basketball',
    activityType: 'Team Sport',
    description: 'Athletes develop basketball fundamentals including shooting, passing, triple threat, scoring moves, and team concepts in a fun and competitive environment. Bring water bottle and proper attire.',
    ageMin: 9,
    ageMax: 12,
    startDate: '2026-04-07',
    endDate: '2026-06-23',
    startTime: '4:35 PM',
    endTime: '5:50 PM',
    days: 'Tue',
    cost: 165,
    costNote: '$165 for the session (Tuesdays, ages 9-12)',
    enrollmentStatus: 'Open',
    registrationDate: null,
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/604972',
    address: MO.address,
    neighbourhood: MO.neighbourhood,
    lat: MO.lat,
    lng: MO.lng,
    city: MO.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=54',
    confirmed2026: MO.confirmed2026,
    priceVerified: MO.priceVerified,
    urlVerified: MO.urlVerified,
    season: 'Spring',
    tags: ['basketball', 'team sport', 'youth'],
    repeating: 'weekly',
    indoorOutdoor: 'Indoor',
  },
  {
    id: 'COV-604973',
    name: 'Basketball - DRIVE Training Academy',
    provider: MO.provider,
    category: 'Sports & Recreation',
    subcategory: 'Basketball',
    activityType: 'Team Sport',
    description: 'Athletes develop basketball fundamentals including shooting, passing, triple threat, scoring moves, and team concepts in a fun and competitive environment. Bring water bottle and proper attire.',
    ageMin: 9,
    ageMax: 12,
    startDate: '2026-04-09',
    endDate: '2026-06-25',
    startTime: '4:35 PM',
    endTime: '5:50 PM',
    days: 'Thu',
    cost: 165,
    costNote: '$165 for the session (Thursdays, ages 9-12)',
    enrollmentStatus: 'Full/Waitlist',
    registrationDate: null,
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/604973',
    address: MO.address,
    neighbourhood: MO.neighbourhood,
    lat: MO.lat,
    lng: MO.lng,
    city: MO.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=54',
    confirmed2026: MO.confirmed2026,
    priceVerified: MO.priceVerified,
    urlVerified: MO.urlVerified,
    season: 'Spring',
    tags: ['basketball', 'team sport', 'youth'],
    repeating: 'weekly',
    indoorOutdoor: 'Indoor',
  },

  // ── Athletic Foundation ──────────────────────────────────────────────────
  {
    id: 'COV-605744',
    name: 'Athletic Foundation',
    provider: MO.provider,
    category: 'Sports & Recreation',
    subcategory: 'Fitness & Training',
    activityType: 'Fitness',
    description: 'Athletic training for youth 13+. Develops speed, agility, plyometrics, and strength through fundamental movement patterns. Progressive, age-appropriate, and structured for long-term physical development.',
    ageMin: 13,
    ageMax: 17,
    startDate: '2026-04-10',
    endDate: '2026-05-29',
    startTime: '6:15 PM',
    endTime: '7:15 PM',
    days: 'Fri',
    cost: 120,
    costNote: '$120 for 8 sessions',
    enrollmentStatus: 'Open',
    registrationDate: null,
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/605744',
    address: MO.address,
    neighbourhood: MO.neighbourhood,
    lat: MO.lat,
    lng: MO.lng,
    city: MO.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=54',
    confirmed2026: MO.confirmed2026,
    priceVerified: MO.priceVerified,
    urlVerified: MO.urlVerified,
    season: 'Spring',
    tags: ['athletics', 'fitness', 'training', 'youth', 'teen'],
    repeating: 'weekly',
    indoorOutdoor: 'Indoor',
  },

  // ── Architecture Camp ────────────────────────────────────────────────────
  {
    id: 'COV-612404',
    name: 'Architecture Around the World Camp with Petit Architect',
    provider: MO.provider,
    category: 'Arts',
    subcategory: 'STEAM',
    activityType: 'STEAM Camp',
    description: 'A global building adventure! Kids explore vernacular architecture from around the world, learning how communities build homes using local materials and sustainable practices. Campers build model homes. Bring nut-free snacks, lunch, and water.',
    ageMin: 7,
    ageMax: 12,
    startDate: '2026-08-04',
    endDate: '2026-08-07',
    startTime: '9:15 AM',
    endTime: '3:00 PM',
    days: 'Tue,Wed,Thu,Fri',
    cost: 375,
    costNote: '$375 for 4-day camp (Tue–Fri)',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-04-08',
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/612404',
    address: MO.address,
    neighbourhood: MO.neighbourhood,
    lat: MO.lat,
    lng: MO.lng,
    city: MO.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=54',
    confirmed2026: MO.confirmed2026,
    priceVerified: MO.priceVerified,
    urlVerified: MO.urlVerified,
    season: 'Summer',
    tags: ['architecture', 'STEAM', 'design', 'hands-on', 'camp'],
    indoorOutdoor: 'Indoor',
  },

  // ── Bowling Out Trip ─────────────────────────────────────────────────────
  {
    id: 'COV-611025',
    name: 'Bowling Out Trip',
    provider: MO.provider,
    category: 'Social & Recreation',
    subcategory: 'Outings',
    activityType: 'Social Outing',
    description: 'Youth bowling outing at the Commodore. Fun, friends, and friendly competition at the lanes. Waiver required. Ages 13–17.',
    ageMin: 13,
    ageMax: 17,
    startDate: '2026-04-17',
    endDate: '2026-04-17',
    startTime: '4:00 PM',
    endTime: '8:00 PM',
    days: 'Fri',
    cost: 12,
    costNote: '$12 per person',
    enrollmentStatus: 'Open',
    registrationDate: null,
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/611025',
    address: MO.address,
    neighbourhood: MO.neighbourhood,
    lat: MO.lat,
    lng: MO.lng,
    city: MO.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=54',
    confirmed2026: MO.confirmed2026,
    priceVerified: MO.priceVerified,
    urlVerified: MO.urlVerified,
    season: 'Spring',
    tags: ['bowling', 'outing', 'youth', 'teen', 'social'],
    indoorOutdoor: 'Indoor',
  },

  // ── Brick Animation Camp ─────────────────────────────────────────────────
  {
    id: 'COV-609960',
    name: 'Brick Animation Camp',
    provider: MO.provider,
    category: 'Arts',
    subcategory: 'Digital Arts',
    activityType: 'STEAM Camp',
    description: 'Create your own stop-motion Brick Animation mini movie using LEGO elements! Learn basic techniques with LEGO Movie Maker including movement, timing, effects, editing, and voice overs.',
    ageMin: 6,
    ageMax: 12,
    startDate: '2026-08-24',
    endDate: '2026-08-28',
    startTime: '10:00 AM',
    endTime: '12:00 PM',
    days: 'Mon,Tue,Wed,Thu,Fri',
    cost: 175,
    costNote: '$175 for 5-day half-day camp',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-04-08',
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/609960',
    address: MO.address,
    neighbourhood: MO.neighbourhood,
    lat: MO.lat,
    lng: MO.lng,
    city: MO.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=54',
    confirmed2026: MO.confirmed2026,
    priceVerified: MO.priceVerified,
    urlVerified: MO.urlVerified,
    season: 'Summer',
    tags: ['LEGO', 'animation', 'stop-motion', 'STEAM', 'camp'],
    indoorOutdoor: 'Indoor',
  },

  // ── Byte Camp programs ───────────────────────────────────────────────────
  {
    id: 'COV-609709',
    name: 'Byte Camp - 2D Animation on Tablet Camp',
    provider: MO.provider,
    category: 'Technology',
    subcategory: 'Digital Arts',
    activityType: 'Technology Camp',
    description: 'Learn 2D animation on tablet in this Byte Camp program. Ages 9-12.',
    ageMin: 9,
    ageMax: 12,
    startDate: '2026-08-04',
    endDate: '2026-08-07',
    startTime: '9:15 AM',
    endTime: '4:15 PM',
    days: 'Tue,Wed,Thu,Fri',
    cost: 355,
    costNote: '$355 for 4-day full-day camp',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-04-08',
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/609709',
    address: MO.address,
    neighbourhood: MO.neighbourhood,
    lat: MO.lat,
    lng: MO.lng,
    city: MO.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=54',
    confirmed2026: MO.confirmed2026,
    priceVerified: MO.priceVerified,
    urlVerified: MO.urlVerified,
    season: 'Summer',
    tags: ['coding', 'animation', 'technology', 'STEAM', 'camp'],
    indoorOutdoor: 'Indoor',
  },
  {
    id: 'COV-609704',
    name: 'Byte Camp - 2D Video Game Design Camp',
    provider: MO.provider,
    category: 'Technology',
    subcategory: 'Game Design',
    activityType: 'Technology Camp',
    description: 'Design and build 2D video games in this Byte Camp program. Ages 11-14.',
    ageMin: 11,
    ageMax: 14,
    startDate: '2026-07-06',
    endDate: '2026-07-10',
    startTime: '9:15 AM',
    endTime: '4:15 PM',
    days: 'Mon,Tue,Wed,Thu,Fri',
    cost: 410,
    costNote: '$410 for 5-day full-day camp',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-04-08',
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/609704',
    address: MO.address,
    neighbourhood: MO.neighbourhood,
    lat: MO.lat,
    lng: MO.lng,
    city: MO.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=54',
    confirmed2026: MO.confirmed2026,
    priceVerified: MO.priceVerified,
    urlVerified: MO.urlVerified,
    season: 'Summer',
    tags: ['coding', 'game design', 'technology', 'STEAM', 'camp'],
    indoorOutdoor: 'Indoor',
  },
  {
    id: 'COV-609716',
    name: 'Byte Camp - 3D Animation Camp',
    provider: MO.provider,
    category: 'Technology',
    subcategory: 'Digital Arts',
    activityType: 'Technology Camp',
    description: 'Learn 3D animation and design in this Byte Camp program. Ages 11-14.',
    ageMin: 11,
    ageMax: 14,
    startDate: '2026-08-24',
    endDate: '2026-08-28',
    startTime: '9:15 AM',
    endTime: '4:15 PM',
    days: 'Mon,Tue,Wed,Thu,Fri',
    cost: 410,
    costNote: '$410 for 5-day full-day camp',
    enrollmentStatus: 'Coming Soon',
    registrationDate: '2026-04-08',
    registrationUrl: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search/detail/609716',
    address: MO.address,
    neighbourhood: MO.neighbourhood,
    lat: MO.lat,
    lng: MO.lng,
    city: MO.city,
    url: 'https://anc.ca.apm.activecommunities.com/vancouver/activity/search?center_ids=54',
    confirmed2026: MO.confirmed2026,
    priceVerified: MO.priceVerified,
    urlVerified: MO.urlVerified,
    season: 'Summer',
    tags: ['coding', '3D animation', 'technology', 'STEAM', 'camp'],
    indoorOutdoor: 'Indoor',
  },
];

// Check for duplicates before adding
const existingIds = new Set(programs.map(p => String(p.id)));
for (const prog of newPrograms) {
  if (existingIds.has(String(prog.id))) {
    console.log(`SKIP (already exists): ${prog.id}`);
  } else {
    programs.push(prog);
    existingIds.add(String(prog.id));
    addCount++;
    console.log(`ADDED: ${prog.id} — ${prog.name}`);
  }
}

fs.writeFileSync(dataPath, JSON.stringify(programs, null, 2) + '\n');
console.log(`\nDone. Fixed: ${fixCount}, Added: ${addCount}, Total: ${programs.length}`);
